const num = 123;

try {
    console.log(numToUpp);
    console.log('Error found');
} catch (error) {
    console.log('Error occcured!');
}

// Output: undefined and Error found